Make Spring integration compatible with Spring Boot 2.4 (#3656)
Motivation:

`org.springframework.boot.actuate.endpoint.OperationArgumentResolver`
has been added in Spring Boot 2.5. We should not use the class if is not
in classpath. `NoClassDefFoundError` will be raised when Spring Boot 2.4
is used.
```java
Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/actuate/endpoint/OperationArgumentResolver
	at com.linecorp.armeria.spring.actuate.ArmeriaSpringActuatorAutoConfiguration.lambda$actuatorServerConfigurator$1(ArmeriaSpringActuatorAutoConfiguration.java:185)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
```

Modifications:

- Extract `acceptHeadersResolver()` to a seperate class so that the
  `OperationArgumentResolver` is lazily loaded only when it is in the
  class path.

Result:

- You no longer see `NoClassDefFoundError` when using Spring integration
  modules with Spring Boot 2.4.