Fix to thread-safely load Thrift classes for libthrift < 0.9.3
Motivation:

In old Thrift versions (< 0.9.3), the multi-thread environment was not
considered during the initialization process for the Thrift class.
A workarournd for that was committed at #4688, but it only applied to
DocService.

This problem can occur not only in `DocService` but also when creating
Thrift clients and other parts, so it would be desirable to use
`ThriftMetadataAccess.getStructMetaDataMap()` for places where
`FieldMetaData.getStructMetaDataMap()` is used.

```java
// When creating Thrift clients
java.lang.IllegalArgumentException: failed to retrieve function metadata: ...
	at com.linecorp.armeria.internal.common.thrift.ThriftServiceMetadata.registerFunction(ThriftServiceMetadata.java:239)
	at com.linecorp.armeria.internal.common.thrift.ThriftServiceMetadata.lambda$init$2(ThriftServiceMetadata.java:117)
	at java.base/java.util.HashMap.forEach(HashMap.java:1337)
	at java.base/java.util.Collections$UnmodifiableMap.forEach(Collections.java:1505)
	at com.linecorp.armeria.internal.common.thrift.ThriftServiceMetadata.init(ThriftServiceMetadata.java:116)
	at com.linecorp.armeria.internal.common.thrift.ThriftServiceMetadata.<init>(ThriftServiceMetadata.java:85)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com.linecorp.armeria.internal.client.thrift.THttpClientDelegate.metadata(THttpClientDelegate.java:216)
	at com.linecorp.armeria.internal.client.thrift.THttpClientDelegate.execute(THttpClientDelegate.java:122)
	at com.linecorp.armeria.internal.client.thrift.THttpClientDelegate.execute(THttpClientDelegate.java:78)
Caused by: java.lang.NullPointerException: null
	at com.linecorp.armeria.internal.common.thrift.ThriftFunction.<init>(ThriftFunction.java:104)
	at com.linecorp.armeria.internal.common.thrift.ThriftFunction.<init>(ThriftFunction.java:66)
	at com.linecorp.armeria.internal.common.thrift.ThriftServiceMetadata.registerFunction(ThriftServiceMetadata.java:229)
	... 33 common frames omitted

// When creating DocService
Caused by: java.lang.NullPointerException: null
	at com.linecorp.armeria.internal.server.thrift.ThriftDescriptiveTypeInfoProvider.newStructInfo(ThriftDescriptiveTypeInfoProvider.java:322)
	at com.linecorp.armeria.internal.server.thrift.ThriftDescriptiveTypeInfoProvider.newDescriptiveTypeInfo(ThriftDescriptiveTypeInfoProvider.java:101)
	at com.linecorp.armeria.server.docs.DocService$SpecificationLoader.lambda$composeDescriptiveTypeInfoProvider$9(DocService.java:386)
```

Referece:
- https://issues.apache.org/jira/browse/THRIFT-1618
- https://github.com/apache/thrift/commit/4a78c6eb8670cbb664a199b1c98518033e51e525

Motifications:

- Replace `FieldMetaData.getStructMetaDataMap()` with
  `ThriftMetadataAccess.getStructMetaDataMap()` to thread-safely
  initialize Thrift classes

Result:

You no longer see `NullPointerException` when creating Thrift clients in
a multi-threaded environment.