Ensure `DnsResolver` is executed by `EventLoop` (#4748)
Motivation:

Implementing #4695, I assumed that a DNS resolver is executed by an event loop.
- `DnsEndpointGroup` schedules DNS queries using an event loop.
https://github.com/line/armeria/blob/10583eb0f34e0de9ef38654d808b1ce3db7eb0c2/core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroup.java#L115
- `RefreshingAddressResolver.doResolve(...)` is invoked by the event loop that is set to `DnsResolverGroupBuilder`.
https://github.com/line/armeria/blob/39efeb240b95c8969c81e94eca8ed07f1f4026df/core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java#L107

However, both assumptions were wrong.
- `DnsEndpointGroup` and `DefaultDnsResolver` can have different event loops if no event loops are specified. Because `DnsEndpointGroupBuilder.eventLoop()` returns a random event loop which is called twice if no executor is configured.
https://github.com/line/armeria/blob/97a17cb1e6671a8b73a61b45b3e460784adcf214/core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroupBuilder.java#L74
- `RefreshingAddressResolver.doResolve(...)` is directly called by the caller thread without switching to an event loop.

This bug may affect the following failure during CI builds.
```
DefaultDnsResolverTest > resolveLessPreferredQuestionFirst(ResolvedAddressTypes) > com.linecorp.armeria.internal.client.dns.DefaultDnsResolverTest.resolveLessPreferredQuestionFirst(ResolvedAddressTypes)[1] FAILED
    java.util.concurrent.CompletionException: com.linecorp.armeria.client.DnsTimeoutException: [] [DefaultDnsQuestion(foo.com. IN A), DefaultDnsQuestion(foo.com. IN AAAA)] is timed out after 5000 milliseconds.
        at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:412)
        at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2044)
        at com.linecorp.armeria.internal.client.dns.DefaultDnsResolverTest.resolveLessPreferredQuestionFirst(DefaultDnsResolverTest.java:172)

        Caused by:
        com.linecorp.armeria.client.DnsTimeoutException: [] [DefaultDnsQuestion(foo.com. IN A), DefaultDnsQuestion(foo.com. IN AAAA)] is timed out after 5000 milliseconds.
```

I am not 100% sure that the exact cause of the problem but the problem has gone after executing the test DNS queries on an event loop.

Modifications:

- Use the event loop bound to the DNS resolver to execute DNS queries.

Result:

Make sure to execute `DnsResolver` in a single thread environment.