Fix DocService by handling Thrift typedefs as an UnresolvedClassInfo (#417)
* Add test case for ThriftServiceSpecificationGenerator typedef-ed type

```
ThriftServiceSpecificationGeneratorTest.servicesTest: FAILURE

com.linecorp.armeria.server.thrift.ThriftServiceSpecificationGeneratorTest > servicesTest FAILED
    java.lang.IllegalArgumentException: unexpected field value type: 12
        at com.linecorp.armeria.server.thrift.ThriftServiceSpecificationGenerator.newTypeInfo(ThriftServiceSpecificationGenerator.java:346)
        at com.linecorp.armeria.server.thrift.ThriftServiceSpecificationGenerator.newFieldInfo(ThriftServiceSpecificationGenerator.java:291)
        at com.linecorp.armeria.server.thrift.ThriftServiceSpecificationGenerator.lambda$newFunctionInfo$9(ThriftServiceSpecificationGenerator.java:251)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.linecorp.armeria.server.thrift.ThriftServiceSpecificationGenerator.newFunctionInfo(ThriftServiceSpecificationGenerator.java:252)
        at com.linecorp.armeria.server.thrift.ThriftServiceSpecificationGenerator.newFunctionInfo(ThriftServiceSpecificationGenerator.java:225)
        at com.linecorp.armeria.server.thrift.ThriftServiceSpecificationGenerator.newServiceInfo(ThriftServiceSpecificationGenerator.java:158)
        at com.linecorp.armeria.server.thrift.ThriftServiceSpecificationGenerator.lambda$generate$4(ThriftServiceSpecificationGenerator.java:129)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at com.linecorp.armeria.server.thrift.ThriftServiceSpecificationGenerator.generate(ThriftServiceSpecificationGenerator.java:126)
        at com.linecorp.armeria.server.thrift.ThriftServiceSpecificationGenerator.generate(ThriftServiceSpecificationGenerator.java:117)
        at com.linecorp.armeria.server.thrift.ThriftServiceSpecificationGeneratorTest.servicesTest(ThriftServiceSpecificationGeneratorTest.java:102)
```

* Handle Thrift typedefs as an UnresolvedClassInfo

Motivation:

The FieldValueMetaData of a typedef'd field does not provide enough
information to infer its effective type. Translate typedef'd field into
a new type called UnresolvedClassInfo so that
ThriftServiceSpecificationGenerator does not fail at least.

Modifications:

- Add UnresolvedClassInfo
- Modify ThriftServiceSpecificationGenerator so that it does not fail on
  a typedef'd field
- Revise @imasahiro's test case to reflect the modification of
  ThriftServiceSpecificationGenerator

Result:

- DocService does not fail to start when typedef is used in .thrift
  files.
- Fixes #413