Fix DocService to handle oneway function properly
Fixes a bug of DocService that it tries to find _result class even for oneway function and end up with exception such as below:
23:23:49.524 [main] WARN com.linecorp.armeria.server.Server - Failed to notify a server listener: com.linecorp.armeria.server.docs.DocService@3590fc5b
java.lang.RuntimeException: unable to initialize Specification
        at com.linecorp.armeria.server.docs.Specification.lambda(Specification.java:87)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at com.linecorp.armeria.server.docs.Specification.forServiceClasses(Specification.java:80)
        at com.linecorp.armeria.server.docs.Specification.forServiceConfigs(Specification.java:70)
        at com.linecorp.armeria.server.docs.DocService.serverStarting(DocService.java:131)
        at com.linecorp.armeria.server.Server.lambda(Server.java:524)
        at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
        at com.linecorp.armeria.server.Server.notifyState(Server.java:520)
        at com.linecorp.armeria.server.Server.enterStarting(Server.java:486)
        at com.linecorp.armeria.server.Server.start(Server.java:225)
        at com.linecorp.armeria.server.Server.start(Server.java:210)
        ...
Caused by: java.lang.ClassNotFoundException: package.HelloService
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at com.linecorp.armeria.server.docs.FunctionInfo.of(FunctionInfo.java:83)
        at com.linecorp.armeria.server.docs.ServiceInfo.of(ServiceInfo.java:60)
        at com.linecorp.armeria.server.docs.Specification.lambda(Specification.java:82)
        ... 11 common frames omitted