Use tryFailure in HttpChannelPool (#2671)
Motivations:
Found this:
```
java.lang.IllegalStateException: complete already: DefaultPromise@7efa5cc1(failure: com.linecorp.armeria.client.SessionProtocolNegotiationException: expected: http, reason: connection established, but session creation timed out: [id: xxxxx)
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:112)
	at com.linecorp.armeria.client.HttpChannelPool.lambda$connect$6(HttpChannelPool.java:424)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	...
```
The `sessionPromise` can be already failed in `HttpSessionHandler` so we should call `tryFailure`, not `setFailure`.