Fix ClassCastException when using Thrift binary type
Motivation:

When a Thrift operation has a parameter or a return value whose type is
binary, a ThriftCallService will fail with a ClassCastException. It is
primarily because TBase.getFieldValue() for a binary field returns a
byte array (byte[]) while TBase.setFieldValue() requires a ByteBuffer.

Also, it is not very easy to figure out the root cause of this sort of
internal server errors because the stack trace of the
TApplicationException shown on the client-side tells a user only the
exception type and message of the server-side exception. There's no way
to get the server-side stack trace.

Modifications:

- Add an internal utility class 'ThriftFieldAccess' which converts a
  byte[] into a ByteBuffer
  - Use it everywhere TBase.getFieldValue() is used.
- When an internal server error occurs, attach the full stack trace of
  the server-side exception.
- Add a test case for a Thrift service with a binary parameter and a
  binary return value
  - ThriftServiceTest
  - ThriftOverHttpClientTest (thanks to @imasahiro)
- Miscellaneous:
  - Remove redundant instantiation of Thrift result object in some case

Result:

- Bug squashed
- Easier tracing at the cost of larger error response. Example:

```
org.apache.thrift.TApplicationException: internal server error:
---- BEGIN server-side trace ----
java.lang.ClassCastException: [B cannot be cast to java.nio.ByteBuffer
        at com.linecorp.armeria.service.test.thrift.main.BinaryService$process_args.setFieldValue(BinaryService.java:401)
        at com.linecorp.armeria.service.test.thrift.main.BinaryService$process_args.setFieldValue(BinaryService.java:252)
        at com.linecorp.armeria.internal.thrift.ThriftFunction.newArgs(ThriftFunction.java:212)
        at com.linecorp.armeria.server.thrift.ThriftCallService.invoke(ThriftCallService.java:104)
        at com.linecorp.armeria.server.thrift.ThriftCallService.serve(ThriftCallService.java:95)
        at com.linecorp.armeria.server.thrift.ThriftCallService.serve(ThriftCallService.java:46)
        at com.linecorp.armeria.server.thrift.THttpService.invoke(THttpService.java:463)
        at com.linecorp.armeria.server.thrift.THttpService.decodeAndInvoke(THttpService.java:436)
        at com.linecorp.armeria.server.thrift.THttpService.lambda$doPost$3(THttpService.java:318)
        at com.linecorp.armeria.common.util.Functions.lambda$voidFunction$1(Functions.java:192)
        at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
        at java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:834)
        at java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2155)
        at com.linecorp.armeria.server.thrift.THttpService.doPost(THttpService.java:311)
        at com.linecorp.armeria.server.http.AbstractHttpService.serve(AbstractHttpService.java:79)
        at com.linecorp.armeria.server.thrift.ThriftServiceTest.invoke0(ThriftServiceTest.java:620)
        at com.linecorp.armeria.server.thrift.ThriftServiceTest.invoke(ThriftServiceTest.java:589)
        at com.linecorp.armeria.server.thrift.ThriftServiceTest.testBinary(ThriftServiceTest.java:529)
        ...
---- END server-side trace ----

        at org.apache.thrift.TApplicationException.read(TApplicationException.java:111)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:79)
        at com.linecorp.armeria.service.test.thrift.main.BinaryService$Client.recv_process(BinaryService.java:88)
        at com.linecorp.armeria.server.thrift.ThriftServiceTest.testBinary(ThriftServiceTest.java:531)
        ...
```