Use BeanFactory's getBean when findBean
Motivation:

- `spring-boot-webflux-starter` app does not start when multiple
`MeterRegistry`s are registerted

```
org.springframework.context.ApplicationContextException: Unable to start reactive web server; nested exception is java.lang.IllegalStateException: Too many MeterRegistry beans: [io.micrometer.cloudwatch.CloudWatchMeterRegistry@6dd79214, io.micrometer.prometheus.PrometheusMeterRegistry@2c47a053, io.micrometer.core.instrument.composite.CompositeMeterRegistry@7767bd4e] (expected: 1)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.onRefresh(ReactiveWebServerApplicationContext.java:82)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:67)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at ...
Caused by: java.lang.IllegalStateException: Too many MeterRegistry beans: [io.micrometer.cloudwatch.CloudWatchMeterRegistry@6dd79214, io.micrometer.prometheus.PrometheusMeterRegistry@2c47a053, io.micrometer.core.instrument.composite.CompositeMeterRegistry@7767bd4e] (expected: 1)
	at com.linecorp.armeria.spring.web.reactive.ArmeriaReactiveWebServerFactory.findBean(ArmeriaReactiveWebServerFactory.java:268)
	at com.linecorp.armeria.spring.web.reactive.ArmeriaReactiveWebServerFactory.configureArmeriaService(ArmeriaReactiveWebServerFactory.java:242)
	at com.linecorp.armeria.spring.web.reactive.ArmeriaReactiveWebServerFactory.lambda$getWebServer$2(ArmeriaReactiveWebServerFactory.java:189)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at com.linecorp.armeria.spring.web.reactive.ArmeriaReactiveWebServerFactory.getWebServer(ArmeriaReactiveWebServerFactory.java:189)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext$ServerManager.<init>(ReactiveWebServerApplicationContext.java:202)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext$ServerManager.get(ReactiveWebServerApplicationContext.java:221)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.createWebServer(ReactiveWebServerApplicationContext.java:90)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.onRefresh(ReactiveWebServerApplicationContext.java:79)
	... 8 common frames omitted
```

Modification:

- Use BeanFactory's getBean when finding a single bean
  - BeanFactory's getBean resolves a primary bean among many of the same type