Clean up flaky tests (#3515)
Motivation:

- A server is restarted in a consul test.
  The restart could be failed because the port bound to the server
  could be acquired by the socket.
  ```
  ConsulEndpointGroupTest > testConsulEndpointGroupWithUrl() FAILED
      java.util.concurrent.CompletionException: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
              at java.base/java.util.concurrent.CompletableFuture.reportJoin(Unknown Source)
          at java.base/java.util.concurrent.CompletableFuture.join(Unknown Source)
          at com.linecorp.armeria.common.util.EventLoopCheckingFuture.join(EventLoopCheckingFuture.java:88)
          at com.linecorp.armeria.client.consul.ConsulEndpointGroupTest.testConsulEndpointGroupWithUrl(ConsulEndpointGroupTest.java:108)

          Caused by:
                  io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
  ```
- A test that stops a server did not wait for the completion of the stopping task

Modifications:

- `ConsulEndpointGroupTest`
  - Lazily create sample endpoints and retry on failure
  - Add a `volatile` keyword where multi-threads could mutate a shared value.
  - Wait until a server finish stopping
- `sse.MainTest`
  - Add `SimpleServerSentMessageDecoder` for Correctly parsing SSE messages from HttpResposne
- `GracefulShutdownIntegrationTest`
  - Relax time bound for waitsForRequestToComplete()

Result:

- Less noisy on CI builds
- Fixes #3513 
- Fixes #3514
- Fixes #3511