Handle a null ExecutionResult in `GraphqlService`
Motivation:

If `GraphQL.execute(input)` returns a `CompletableFuture` completing
exceptionally, `NullPointException` is raised while handling `ExecutionResult`.
```java
java.lang.NullPointerException: Cannot invoke "graphql.ExecutionResult.getData()" because "executionResult" is null
	at com.linecorp.armeria.server.graphql.DefaultGraphqlService.lambda$execute$1(DefaultGraphqlService.java:117)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
```

Modifications:

- Check if `cause != null` before accessing `executionResult` in the
  callback of `executeGraphql(ctx, input)`.

Result:

- `NullPointerException` is no longer raised when `GraphqlService` handles errors.
- Closes #5815