Throws error when annotated services have suspend fun without `armeria-kotlin` (#3020)
Motivation:
Without the `armeria-kotlin` dependency, Armeria cannot invoke Kotlin suspending methods defined in annotated services,
and the error messages are difficult to understand.

This is one of current error messages.
(Compiled suspending functions have `kotlin.coroutines.Continuation` as a parameter)

```
java.lang.IllegalArgumentException: failed to parse a JSON document: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `kotlin.coroutines.Continuation` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (String)"{}"; line: 1, column: 1]
...
```

Modifications:
`AnnotatedServiceFactory.create` checks if a given method is suspending.
If the method is suspending and `armeria-kotlin` is missing, Armeria throws an exception with the message
```
Kotlin suspending functions cannot be used. You should add the armeria-kotlin dependency
```

 and don't start an application.

<details>
  <summary>full error message</summary>
  
```
Exception in thread "main" java.lang.IllegalArgumentException: Kotlin suspending functions cannot be used. You should add the armeria-kotlin dependency.
	at com.linecorp.armeria.internal.server.annotation.AnnotatedServiceFactory.create(AnnotatedServiceFactory.java:246)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedServiceFactory.lambda$find$0(AnnotatedServiceFactory.java:184)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedServiceFactory.find(AnnotatedServiceFactory.java:187)
	at com.linecorp.armeria.server.AnnotatedServiceBindingBuilder.buildServiceConfigBuilder(AnnotatedServiceBindingBuilder.java:262)
	at com.linecorp.armeria.server.VirtualHostBuilder.lambda$build$8(VirtualHostBuilder.java:890)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.linecorp.armeria.server.VirtualHostBuilder.build(VirtualHostBuilder.java:901)
	at com.linecorp.armeria.server.ServerBuilder.build(ServerBuilder.java:1452)
	at example.armeria.server.annotated.kotlin.MainKt.newServer(Main.kt:39)
	at example.armeria.server.annotated.kotlin.MainKt.main(Main.kt:12)
```
</details>

Result:
- Fixes #3018 
- Users who want use Kotlin coroutines with annotated services can notice that the `armeria-kotlin` dependency is needed.