Fix flaky `HttpServerRequestTimeoutTest`
Motivation:

```
HttpServerRequestTimeoutTest > setRequestTimeoutAfterNoTimeout() FAILED
    java.util.concurrent.CompletionException: com.linecorp.armeria.common.stream.ClosedStreamException: received a RST_STREAM frame: INTERNAL_ERROR
        at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:412)
        at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2108)
        at com.linecorp.armeria.common.util.EventLoopCheckingFuture.join(EventLoopCheckingFuture.java:88)
```

An `OverflowException` could be raised when using `Flux.interval(...)`
See #3525 for details

Modifications:

- Add `onBackpressureDrop()` where `Flux.interval()` is used to generate
  a response content.

Result:

Fixes #3557