Fix `:core:shadedClasses` failure
Motivation:

':core:shadedClasses' fails when JaCoCo report is enabled by
`-Pcoverage`.
```java
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':core:shadedClasses'.
  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:135)
  at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:288)
  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:133)
  ...
  at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
  at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
Caused by: org.gradle.api.InvalidUserDataException: Cannot expand ZIP '/home/runner/work/armeria/armeria/core/build/libs/armeria-1.33.3-SNAPSHOT-shaded.jar' as it does not exist.
```

It is difficult to analyze why the test fails when JaCoCo is enabled,
but it seems the `archiveClassifier.set('shaded')` configuration used when
upgrading Gradle 9 is causing the problem.
Based on the following two configurations, the path of archiveFile
becomes `<artifact>-untrimmed-<version>-shaded.jar`.
https://github.com/line/armeria/blob/7148df07f3a7fe7cb4640fb1ca761cbaca8b347f/gradle/scripts/lib/java-shade.gradle#L28
https://github.com/line/armeria/blob/7148df07f3a7fe7cb4640fb1ca761cbaca8b347f/gradle/scripts/lib/java-shade.gradle#L118

This is then renamed to `<artifact>-shaded-<version>-shaded.jar` by
`trimShadedJar` task. However, since the input file of `shadedClasses` is
`<artifact>-<version>-shaded.jar`, the task fails to fine the jar file.

Modifications:

- Generate the output file name correctly by removing `untrimmed` infix
  from the output jar file instead of renaming it to `shaded`.

Result:

`:core:shadedClasses` runs correctly