Workaround for pgv regex rewrite issue (#6714)
Motivation:

Recently, two regex patterns have been added upstream:


https://github.com/envoyproxy/envoy/blob/0baaeb4a832cd5683b221cea98b05ed139b3e332/api/envoy/extensions/filters/http/oauth2/v3/oauth.proto#L148-L149

https://github.com/envoyproxy/envoy/blob/0baaeb4a832cd5683b221cea98b05ed139b3e332/api/envoy/extensions/filters/http/oauth2/v3/oauth.proto#L49

Unfortunately, this results in an error due to invalid java conversion:
```
/Users/user/Projects/armeria/xds-api/build/generated/sources/proto/main/javapgv/io/envoyproxy/envoy/extensions/filters/http/oauth2/v3/CookieConfigValidator.java:20: error: illegal start of expression
                com.google.re2j.Pattern PATH__PATTERN = com.google.re2j.Pattern.compile("^$|^/[^\\x00-\\x1f\\x7f \\",;<>\\\\]*$");
```

Where the conversion logic can be found here:

https://github.com/bufbuild/protoc-gen-validate/blob/92b9a7df69ca9f71bfc492f7a90adf4d36eab569/templates/java/register.go#L442

The core issue is regex patterns are rewritten to `\\\xHH`, `\\"` both
of which are invalid.
As a workaround, I propose that invalid regex patterns are manually
rewritten after pgv generation

Modifications:

- Added a step to rewrite invalid regex after pgv generation in
`:xds-api`

Result:

- xDS protobuf files can be updated again

<!--
Visit this URL to learn more about how to write a pull request
description:

https://armeria.dev/community/developer-guide#how-to-write-pull-request-description
-->