Add debug logs for http2 stream errors (#4515)
Motivation:

We sometimes encounter situations where  HTTP/2 header frames are lost due to an exception.
Although a RST frame is sent in this case, remotes are still able to send data for the offending stream, which ends up in error logs which armeria doesn't understand.

e.g.
```
io.netty.handler.codec.http2.Http2Exception: Stream 1147 does not exist
```

Although normally it might be noisy to be alerted of such failures, it might be useful to view such logs when debugging.

Modifications:

- Added logging for HTTP/2 `StreamError`
- Added logging for connection errors just in case as well.

Result:

- Easier to debug http2 failure logs.