Use `Iterator.remove()` to remove pending futures in `AbstractEndpointSelector`
Motivation:

Calling `Collection.remove(T)` while interacting a `Collection` may
result in `ConcurrentModificationException` or `NullPointerException`.
`Iterator.remove()` is recommended to remove an item while iteration.

A pending future in `AbstractEndpointSelector` may be removed from
`pendingFutures` with `pendingFutures.remove()` while iterating as
new `Endpoint`s are updated.

```
NullPointerException: Cannot invoke "com.linecorp.armeria.client.endpoint.AbstractEndpointSelector$ListeningFuture.accept(java.lang.Void)" because "future" is null
	at com.linecorp.armeria.client.endpoint.AbstractEndpointSelector.refreshEndpoints(AbstractEndpointSelector.java:154)
	at com.linecorp.armeria.common.util.AbstractListenable.notifyListeners(AbstractListenable.java:60)
```

Modifications:

- Refactored `ListeningFuture` not to remove itself from pending futures
  when an endpoint is selected.
  - `tryComplete()` reports the result of `Endpoint` selection and the
    future may be removed by the caller with `Iterator.remove()`.

Result:

You no longer see `NullPointerException` when an `Endpoint` is selected
from `EndpointGroup`