Fix NullPointerException from re-entrant logging in Logback 1.5 (#6662)
Motivation:

There is an circular dependency: a log emitted during
`RequestContextStorage` initialization in
`RequestContextExportingAppender.append()` re-enters `.append()` and
leads to a `NullPointerException`.
```
java.lang.NullPointerException: Cannot invoke "com.linecorp.armeria.common.RequestContextStorage.currentOrNull()" because "com.linecorp.armeria.internal.common.RequestContextUtil.requestContextStorage" is null
  at com.linecorp.armeria.internal.common.RequestContextUtil.get(RequestContextUtil.java:142)
  at com.linecorp.armeria.common.RequestContext.currentOrNull(RequestContext.java:91)
  at com.linecorp.armeria.common.logging.RequestContextExporter.export(RequestContextExporter.java:204)
  at com.linecorp.armeria.common.logback.RequestContextExportingAppender.append(RequestContextExportingAppender.java:213)
  at com.linecorp.armeria.common.logback.RequestContextExportingAppender.append(RequestContextExportingAppender.java:57)
  at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:81)
  at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
  at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:272)
  at ch.qos.logback.classic.Logger.callAppenders(Logger.java:259)
  at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:431)
  at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:388)
  at ch.qos.logback.classic.Logger.log(Logger.java:805)
  at io.netty.util.internal.logging.LocationAwareSlf4JLogger.log(LocationAwareSlf4JLogger.java:50)
  at io.netty.util.internal.logging.LocationAwareSlf4JLogger.debug(LocationAwareSlf4JLogger.java:108)
  at io.netty.util.internal.InternalThreadLocalMap.<clinit>(InternalThreadLocalMap.java:99)
  at io.netty.util.concurrent.FastThreadLocal.<init>(FastThreadLocal.java:129)
  at com.linecorp.armeria.common.ThreadLocalRequestContextStorage.<clinit>(ThreadLocalRequestContextStorage.java:31)
  at com.linecorp.armeria.common.RequestContextStorage.threadLocal(RequestContextStorage.java:87)
  at com.linecorp.armeria.common.DefaultFlagsProvider$1.newStorage(DefaultFlagsProvider.java:144)
  at com.linecorp.armeria.internal.common.RequestContextUtil.<clinit>(RequestContextUtil.java:73)
  at com.linecorp.armeria.common.RequestContext.currentOrNull(RequestContext.java:91)
  at com.linecorp.armeria.common.logging.RequestContextExporter.export(RequestContextExporter.java:204)
  at com.linecorp.armeria.common.logback.RequestContextExportingAppender.append(RequestContextExportingAppender.java:213)
  at com.linecorp.armeria.common.logback.RequestContextExportingAppender.append(RequestContextExportingAppender.java:57)
  at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:81)
  at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
  at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:272)
  at ch.qos.logback.classic.Logger.callAppenders(Logger.java:259)
  at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:431)
  at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:388)
  at ch.qos.logback.classic.Logger.log(Logger.java:805)
  at io.netty.util.internal.logging.LocationAwareSlf4JLogger.log(LocationAwareSlf4JLogger.java:50)
  at io.netty.util.internal.logging.LocationAwareSlf4JLogger.debug(LocationAwareSlf4JLogger.java:108)
  at io.netty.channel.MultithreadEventLoopGroup.<clinit>(MultithreadEventLoopGroup.java:44)
```

It is likely due to a change in Logback 1.5.21 that enables re-entry by
default.

https://github.com/qos-ch/logback/commit/04a7ba558c393070c2eb2c78a1a999ba19d482ee

The recommended approach is to use
`ReentryGuardFactory.GuardType.THREAD_LOCAL`, which prevents re-entrant
calls on a per-thread basis. However, we can't use this API in
`RequestContextExportingAppender` because it was introduced in Logback
1.5.21 and `RequestContextExportingAppender` is shared across multiple
Logback versions.

For that reason, I reordered of static field initialization to avoid the
`NullPointerException` rather than copying the implementation and
introducing duplicate code.

Modifications:

- Initialize `RequestContextUtil` before Flags are fully loaded.

Result:

`RequestContextExportingAppender` no longer throws a
`NullPointerException` during `RequestContextStorage` initialization in
Logback 1.5.21 and later.