Allow HttpFile to pass a Spring Boot 3 nested jar URL (#5391)
Motivation:

After zipkin upgraded to spring boot, our UI failed to load due to an unanticipated URL format:

```
java.lang.IllegalArgumentException: Unsupported URL: jar:nested:/Users/adrian/oss/zipkin/zipkin-server/target/zipkin-server-3.0.4-SNAPSHOT-exec.jar/!BOOT-INF/lib/zipkin-lens-3.0.4-SNAPSHOT.jar!/zipkin-lens/static/css/main.311b483b.css (must start with 'file:', 'jar:file', 'jrt:' or 'bundle:')
	at com.linecorp.armeria.server.file.HttpFile.builder(HttpFile.java:206) ~[!/:?]
	at com.linecorp.armeria.server.file.HttpFile.builder(HttpFile.java:230) ~[!/:?]
	at com.linecorp.armeria.server.file.ClassPathHttpVfs.blockingGet(ClassPathHttpVfs.java:58) ~[armeria-1.26.4.jar!/:?]
	at com.linecorp.armeria.server.file.AbstractBlockingHttpVfs.lambda$get$0(AbstractBlockingHttpVfs.java:82) ~[armeria-1.26.4.jar!/:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at com.linecorp.armeria.common.DefaultContextAwareRunnable.run(DefaultContextAwareRunnable.java:45) ~[armeria-1.26.4.jar!/:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

Modifications:

- Change HttpFile to pass the custom classpath "nested" type defined by spring

Result:

- Closes #5390
- nested classpath URLs work with HttpFile