Update public suffix list with pull requests
Motivation:

`update-psl` fails to push changes to the master branch because the branch
is protected after [Merge Queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue)
is enabled.

```
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error:
To https://github.com/line/armeria
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/line/armeria'
Error: Invalid status code: 1
```

Modifications:

- Automatically create a pull request for new changes in
  `public_suffixes.txt`
- The created PR is also automatically merged by [Mergify](https://mergify.com).

Result:

New public suffixes are correctly updated to `public_suffixes.txt`.