Reject DATA Frames for invalid path requests
Motivation:

If a request with an invalid path such as `/?download=../../secret.txt`
and a DATA Frame is received, a `ClassCastException` can be raised.
```
java.lang.ClassCastException: class com.linecorp.armeria.server.EmptyContentDecodedHttpRequest cannot be cast to class com.linecorp.armeria.server.DecodedHttpRequestWriter (com.linecorp.armeria.server.EmptyContentDecodedHttpRequest and com.linecorp.armeria.server.DecodedHttpRequestWriter are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @301eda63)
  at com.linecorp.armeria.server.Http2RequestDecoder.onDataRead(Http2RequestDecoder.java:265)
  at io.netty.handler.codec.http2.Http2FrameListenerDecorator.onDataRead(Http2FrameListenerDecorator.java:36)
  at io.netty.handler.codec.http2.Http2EmptyDataFrameListener.onDataRead(Http2EmptyDataFrameListener.java:49)
  at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:307)
  at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48)
```
Although a response is immediately sent by `HttpServerHandler` for
the invalid path when the headers are received and try to close the stream,
`onDataRead()` callback could be triggered by the following DATA frame.
Because the stream could not be closed yet.
https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java#L242-L244

Modification:

- Rejects the following DATA frames and HEADERS frames of invalid path
  requests with `PROTOCOL_ERROR`.

Result:

You no longer see `ClassCastException` when an invalid path request is
recevied.