Less verbose error logging / Fix incorrect behavior when 'verboseExceptions' is set. (#1529)
Motivation:

1. `Exceptions.isExpected(Throwable)` should always return `false` when
   `verboseExceptions` flag is set. However, it currently always returns
   `true` by coding mistake.
2. I found a few more exception messages which do not really need to be
   logged at high level:

       SSLException: SSLEngine closed already
       Sent a GOAWAY frame: lastStreamId=..., errorCode=INTERNAL_ERROR(2), debugData="Error flushing"

Both errors can happen when a socket connection has been closed by a
remote peer, which should be treated in a similar manner with
'connection reset by peer' errors.

Modifications:

- Update `Exceptions.isExpected()` to always return `false` when
  `verboseExceptions` flag is set.
- Update `Exceptions.isExpected()` to return `true` for
  `SSLException: SSLEngine closed already`.
- Update `Http2GoAwayHandler` to log at DEBUG level for
  `Sent a GOAWAY frame: ... debugData="Error flushing"`.

Result:

- Fixes #1515
- `com.linecorp.armeria.verboseExceptions` flag works as expected.
- Cleaner log file with less WARN-level log messages.