Fix failed Athenz tests
Motivation:

Athenz ZTS server defined in the Docker Compose file fails to start up
because of changes introduced in Athenz 1.12.28.
```java
WARN  o.e.jetty.ee10.webapp.WebAppContext - Failed startup of context oeje10w.WebAppContext@79f227a9{zts,/zts,b=file:///tmp/jetty-0_0_0_0-8443-zts_war-_zts-any-1237552957018305555/webapp/,a=AVAILABLE,h=oeje10s.SessionHandler@14f3c6fc{STARTED}}{/opt/athenz/zts/webapps/zts.war}
jakarta.servlet.ServletException: zts-server==org.glassfish.jersey.servlet.ServletContainer@5aa3f717{jsp=null,order=1,inst=true,async=true,src=DESCRIPTOR:file:///tmp/jetty-0_0_0_0-8443-zts_war-_zts-any-1237552957018305555/webapp/WEB-INF/web.xml,STARTED}
...
Caused by: com.yahoo.athenz.auth.util.CryptoException: Invalid jwks uri: athenz-zts-server/oauth2/keys?rfc=true
	at com.yahoo.athenz.auth.token.jwts.JwtsSigningKeyResolver.addKeySource(JwtsSigningKeyResolver.java:181)
	at com.yahoo.athenz.auth.token.jwts.JwtsSigningKeyResolver.addJwksUriKeySource(JwtsSigningKeyResolver.java:140)
	at com.yahoo.athenz.auth.token.jwts.JwtsSigningKeyResolver.createKeyResolver(JwtsSigningKeyResolver.java:135)
	at com.yahoo.athenz.auth.token.jwts.JwtsSigningKeyResolver.<init>(JwtsSigningKeyResolver.java:92)
	at com.yahoo.athenz.auth.token.jwts.JwtsHelper.getJWTProcessor(JwtsHelper.java:241)
	at com.yahoo.athenz.zts.ZTSImpl.loadJWTProcessors(ZTSImpl.java:501)
	at com.yahoo.athenz.zts.ZTSImpl.<init>(ZTSImpl.java:412)
	at com.yahoo.athenz.zts.ZTSImpl.<init>(ZTSImpl.java:289)
	at com.yahoo.athenz.zts.ZTSImplFactory.<clinit>(ZTSImplFactory.java:20)
	... 75 common frames omitted
```

It seems that a valid jwks_url is required in zts.property to start the
server correctly. If it is not set, the system hostname is used instead,
which leads a `MalformedURLException`.

Modifications:

- Set `https://athenz.io` as a dummy oauth_issuer in zts.properties
- Use athenz/athenz-zts-db:latest for the base image of zts-db
  - Using athenz-zms-db works by initializing it with `/zts-init-db.sql`,
    but it’s not the intended value.

Result:

Revive broken Athenz tests