Fix flaky test in `ZooKeeperRegistrationTest.curatorRegistrationSpec()` (#3210)
Motivation:

Occasionally ZooKeeperRegistrationTest failed because of a duplicate port number.

```java
ZooKeeperRegistrationTest > curatorRegistrationSpec() FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in com.linecorp.armeria.common.zookeeper.ZooKeeperTestUtil that uses com.linecorp.armeria.server.Server
    Expecting code not to raise a throwable but caught
      <"java.util.concurrent.CompletionException: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
```

Modifications:

- Allocate a new port if a server fails to start

Result:

- Clean up flaky tests