Fix a regression where response exceptions are logged unintentionally (#6035)
Motivation:

We've received reports that the following log message is printed, and also exposed when completing the response exceptionally.
```
Unexpected exception while closing a request:
com.linecorp.armeria.client.UnprocessedRequestException: com.linecorp.armeria.client.GoAwayReceivedException
    at com.linecorp.armeria.client.UnprocessedRequestException.of(UnprocessedRequestException.java:45)
    at com.linecorp.armeria.client.Http2ResponseDecoder.onStreamClosed(Http2ResponseDecoder.java:146)
```

It seems like this is a regression of the refactoring done at: https://github.com/line/armeria/pull/5800/files#diff-d82983b1c20c5f80257da8c39bb74a80d49e81efceb7a1ce63847776de9b40a9R255

I propose that if an exception completes the corresponding `HttpResponse` and `RequestLog`, then we don't log the exception in `HttpResponseWrapper`

Modifications:

- `boolean DefaultStreamMessage#tryClose` has been added which signals whether the call closed the `StreamMessage`
- the `CancelledSubscriptionException` check has been moved to `tryClose` for more consistent behavior
- If `HttpResponseWrapper#closeAction` actually closed the response, then return early so that a log isn't printed
- Added a test as a separate module to avoid flakiness due to parallel test runs

Result:

- Unnecessary logs aren't left from `HttpResponseWrapper`

<!--
Visit this URL to learn more about how to write a pull request description:
https://armeria.dev/community/developer-guide#how-to-write-pull-request-description
-->