Fix a `NullPointerException` raised while an aborted `FixedStreamMessage` is being collected. (#4652)
Motivation:

We got a report about `NullPointerException` from LINE internally.
```
java.lang.NullPointerException: at index 0
	at com.linecorp.armeria.internal.shaded.guava.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:229)
	at com.linecorp.armeria.internal.shaded.guava.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:219)
	at com.linecorp.armeria.internal.shaded.guava.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:213)
	at com.linecorp.armeria.internal.shaded.guava.collect.ImmutableList.construct(ImmutableList.java:353)
	at com.linecorp.armeria.internal.shaded.guava.collect.ImmutableList.of(ImmutableList.java:109)
	at com.linecorp.armeria.internal.common.stream.TwoElementFixedStreamMessage.drainAll(TwoElementFixedStreamMessage.java:75)
	at com.linecorp.armeria.internal.common.stream.FixedStreamMessage.collect(FixedStreamMessage.java:201)
	at com.linecorp.armeria.internal.common.stream.FixedStreamMessage.lambda$collect$2(FixedStreamMessage.java:188)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

The error occured because the elements of a `StreamMessage` are null when a `StreamMessage.collect()` is called. Double subscriptions aren't the cause of the problem since it is atomically checked by CAS operations.

One possible senario is `abort()` is called first and `collect()` is called right after. The two method calls are not thread safe because the `abort()` called first can't get a executor which is assigned when `subscribe()` is called. As a result, a direct executor is used and then two threads may access the elements simultaneously.

Modifications:

- Remove `subscribedUpdater` and use `executorUpdater` as a latch for a concurrent execution.
- Make `abort()` executed directly only when explicitly there is no subscription.
  - If a executor has already been assigned by another thread, the executor is used to avoid the race condition.

Result:

You no longer see `NullPointerException` when an aborted `StreamMessage` is collected.