Fix a bug where an EndpointGroup listener is not invoked
Motivation:

`WeightedRoundRobinStrategy` fails to select an `Endpoint` from a
non-empty `EndpointGroup`.
```
c.l.a.c.UnprocessedRequestException: c.l.a.c.e.EndpointSelectionTimeoutException:
  Failed to select within 5000 ms an endpoint from: DnsAddressEndpointGroup{selectionStrategy=class
  com.linecorp.armeria.client.endpoint.WeightedRoundRobinStrategy, allowsEmptyEndpoints=false, initialized=true, numEndpoints=1,
  endpoints=[Endpoint{xxx.com:8443, ipAddr=xxx.xxx.xxx.xxx, weight=1000}], questions=[DnsQuestion(xxx.com. IN A)], logPrefix=xxx.com., attemptsSoFar=0}
	at com.linecorp.armeria.client.UnprocessedRequestException.of(UnprocessedRequestException.java:45)
	at com.linecorp.armeria.client.HttpClientDelegate.earlyFailedResponse(HttpClientDelegate.java:228)
	at com.linecorp.armeria.client.HttpClientDelegate.execute(HttpClientDelegate.java:66)
	at com.linecorp.armeria.client.HttpClientDelegate.execute(HttpClientDelegate.java:51)
```

Through static analysis, I found out that a race condition exists in
our `Endpoint` selection logic.

1. `ListeningFuture` receives a notification of updated endpoints and
   attempts to select endpoints.
   https://github.com/line/armeria/blob/d5f65e5a3703282fe28b8336628079a1d32f161d/core/src/main/java/com/linecorp/armeria/client/endpoint/AbstractEndpointSelector.java#L139
2. They are the intial endpoints. As `EndpointSelector` is lazily created,
   `DynamicEndpointGroup` creates the EndpointSelector first.
   https://github.com/line/armeria/blob/d5f65e5a3703282fe28b8336628079a1d32f161d/core/src/main/java/com/linecorp/armeria/client/endpoint/DynamicEndpointGroup.java#L195
3. In `EndpointSelector` constructor, it adds a new listener in order to
   get the current endpoints. The new listener is added while the
   orignal lisnter is invoked.
   https://github.com/line/armeria/blob/d5f65e5a3703282fe28b8336628079a1d32f161d/core/src/main/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategy.java#L59-L62
4. After all listeners is called, `initialEndpointsFuture` is completed.
   Thus the listener added in 3) can't immediately be called despite the
   presence of current endpoints. Because `latestValue()` returns the
   enpdopints when `initialEndpointsFuture` is completed.
   https://github.com/line/armeria/blob/d5f65e5a3703282fe28b8336628079a1d32f161d/core/src/main/java/com/linecorp/armeria/client/endpoint/DynamicEndpointGroup.java#L226-L227
   https://github.com/line/armeria/blob/863e27c5268631360c14e50e13cd3e38d84c9db5/core/src/main/java/com/linecorp/armeria/client/endpoint/AbstractEndpointGroup.java#L27-L28
5. As a result of 4), endpointsAndWeights remains null, causing selectNow(ctx) to return null.
   https://github.com/line/armeria/blob/d5f65e5a3703282fe28b8336628079a1d32f161d/core/src/main/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategy.java#L67-L70

Motifications:

- Override `latestValue()` in `DynamicEndpointGroup` to directly access
  `endpoints` without seeing the result of `whenReady()`.

Result:

You no longer see a false postive `EndpointSelectionTimeoutException`
when `EndpointSelectionStrategy.weightedRoundRobin()` is used with
`DynamicEndpointGroup`.