Fix flaky tests in `DnsMetricsTest` (#3498)
We have shown the following flaky test on DNS metrics since we moved CI builds to GitHub Actions with self-hosted runners.
```
DnsMetricsTest > nxDomain() FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in com.linecorp.armeria.client.DnsMetricsTest that uses io.micrometer.core.instrument.MeterRegistry, io.micrometer.core.instrument.MeterRegistryjava.lang.String
    Expecting map:
     <{"armeria.client.dns.queries#count{cause=nx_domain,name=bar.com.,result=failure}"=1.0, "armeria.client.dns.queries.written#count{name=bar.com.,server=0:0:0:0:0:0:0:1}"=1.0}>
    to contain:
     <[MapEntry[key="armeria.client.dns.queries.written#count{name=bar.com.,server=0:0:0:0:0:0:0:1}", value=2.0]]>
    but could not find the following map entries:
     <[MapEntry[key="armeria.client.dns.queries.written#count{name=bar.com.,server=0:0:0:0:0:0:0:1}", value=2.0]]>
     within 10 seconds.
        at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:165)
        at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
        at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
        at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:895)
        at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:679)
        at com.linecorp.armeria.client.DnsMetricsTest.nxDomain(DnsMetricsTest.java:205)

        Caused by:
        java.lang.AssertionError:
        Expecting map:
         <{"armeria.client.dns.queries#count{cause=nx_domain,name=bar.com.,result=failure}"=1.0, "armeria.client.dns.queries.written#count{name=bar.com.,server=0:0:0:0:0:0:0:1}"=1.0}>
        to contain:
         <[MapEntry[key="armeria.client.dns.queries.written#count{name=bar.com.,server=0:0:0:0:0:0:0:1}", value=2.0]]>
        but could not find the following map entries:
         <[MapEntry[key="armeria.client.dns.queries.written#count{name=bar.com.,server=0:0:0:0:0:0:0:1}", value=2.0]]>
            at com.linecorp.armeria.client.DnsMetricsTest.lambda$nxDomain$7(DnsMetricsTest.java:207)
```
If a DNS query is failed to resolve an IP address, Netty DNS resolver tries to resolve a CNAME record.
However, the test result shows the resolver attempts to resolve only once.

Dug into the problem and found out that Netty uses `/etc/resolve.conf` as a default configuration if exists.
`/etc/resolve.conf` in our self-hosted CI servers is configured with `options timeout:1 attempts:1`.

Modifications:

- Explicitly set default values to `DnsResolverGroupBuilder` to avoid
  flakiness raised by different options in `/etc/resolve.conf`
- Fix a flaky test in `RefreshingAddressResolverTest`
- CI Build configuration
  - Revert `-PnoWeb` for all CI builds
  - Exclude Kotlin files from JaCoCo report
    - There is an incompatibility between JaCoCo and Kotlin 1.5.0.
      We upgraded Kotlin version to 1.5.0 in Armeria 1.7.0.
	  Because of unstable CI status, we didn't catch it at the time.
      https://github.com/line/armeria/pull/3487/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R9

Result:

- Less noise in CI builds
- Fixes #3491